apiVersion: {{ .Values.api.ingress | default "networking.k8s.io/v1" | quote }}
kind: Ingress
metadata:
  name: testing-office-ingress-bot
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "ingress-nginx-office"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: 4096m
  labels:
    app: testing-office-ingress-bot
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: "ingress-nginx-office"  
  rules:
  - host: "devtools-dev-outline-bot.sprinklr.com"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: dev-bot-helm
              port:
                number: {{ .Values.service.frontendPort }}
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: dev-bot-helm
              port:
                number: {{ .Values.service.backendPort }}

